# Generated by Django 4.2.7 on 2025-06-23 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='The unique identifier for the page URL.', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show_storefront_tab', models.BooleanField(default=False)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='page_backgrounds/')),
                ('template_theme', models.CharField(choices=[('default', 'Default'), ('dark_mode', 'Dark Mode'), ('misty_rose', 'Misty Rose')], default='default', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('header', 'Header'), ('links', 'Links'), ('carousel', 'Carousel'), ('video', 'Video'), ('paywall', 'Paywall'), ('courses', 'Courses'), ('events', 'Events'), ('masterclass', 'Masterclass/Webinar'), ('appointments', 'One-on-one Appointments')], max_length=20)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order of section on the page, managed by drag-and-drop.')),
                ('is_enabled', models.BooleanField(default=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
