# Generated by Django 4.2.7 on 2025-06-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='brand_name',
            field=models.CharField(default='mega', help_text='Your unique brand name. This will be used in your page URL.', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, help_text='e.g., Fitness Coach, Digital Artist, Podcaster', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
