# Generated by Django 4.2.7 on 2025-06-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_brand_name_page_title_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('header', 'Header'), ('links', 'Links'), ('carousel', 'Carousel'), ('video_carousel', 'Video Carousel'), ('paywall', 'Paywall'), ('courses', 'Courses'), ('events', 'Events'), ('masterclass', 'Masterclass/Webinar'), ('appointments', 'One-on-one Appointments')], max_length=20),
        ),
    ]
