# Generated by Django 4.2.7 on 2025-07-01 13:00

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_section_section_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='page',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='page',
            name='template_theme',
        ),
        migrations.AddField(
            model_name='page',
            name='theme_settings',
            field=models.JSONField(default=pages.models.get_default_theme),
        ),
    ]
