# Generated by Django 4.2.7 on 2025-07-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_page_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='show_storefront_tab',
        ),
        migrations.AddField(
            model_name='page',
            name='display_mode',
            field=models.CharField(choices=[('page_only', 'Page Only'), ('store_only', 'Store Only'), ('both', 'Both Page and Store')], default='page_only', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='brand_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
