# Generated by Django 4.2.7 on 2025-07-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_page_show_storefront_tab_page_display_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='bank_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='subaccount_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
